### ISSUE TITLE
Can't build the project

### ISSUE THREAD

**Issue by adam-borkowski** [MpicoSys/USB2TCM#1]
Project looks to be incomplete. Processor Expert .pe file is missing so peripherals drivers can't be generated. It was checked in Kinetis Design Studio 2.0.0 but probably won't work also in CodeWarrior IDE.

**Comment by admin-MpicoSys** [comment]
Added missing ProcessorExpert configuration files (works with CodeWarrior IDE v10.6).

**Comment by adam-borkowski** [comment]
Thanks for adding processor expert .pe file. Other files like .g_c and .g_x are not required to be versioned.
I have generated Processor Expert libraries. By the way, generation of TCM component was disabled.
Was it made intentionally? Does this files contain some custom modifications, which was not intendet to be modified by Processor Expert generation?
Trying to build shown another issue with undefined reference to **TCM_SendReceiveBlock()** function in TCM_api.c.

**Comment by aleksander-gajewski** [comment]
Added missing TCM_SendReceiveBlock() function in independent library.
